### ISSUE TITLE
Miner: Verify that duplicate submissions of consensus faults are not processed

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#1008]
From the code: 

https://github.com/filecoin-project/specs-actors/blob/ca1b7724d3016313f76c583c4f1110fe1e58ef7d/actors/builtin/miner/miner_actor.go#L1414-L1417

Given that miners are no longer terminated on consensus faults, this method should ensure that submitted faults are unique.

**Comment by anorth** [comment]
cc @nicola @ZenGround0

**Comment by wadeAlexC** [comment]
I know this has been raised outside of actors, but I just had an idea for this --

`ReportConsensusFault` could track the "newest fault," and abort if a submitted report is older than the "newest fault."

**Comment by wadeAlexC** [comment]
Though I'm not sure if that would allow miners to create older consensus faults at will... I guess they could, but they'd also have to accept at least 1 penalty.

The biggest problem I have with this method is that it feels most likely a miner will report themselves, since they're the first to be aware of a consensus fault. With the current way IP is treated, this is a vector to allow a miner to drain funds that (IMO) should be locked as IP.

Especially if a miner intends to move to a new fork (and trash the old chain), they're currently incentivized to report themselves for lots of consensus faults in order to cut their losses (as they'd eventually get reported anyway).

Also, keep in mind that miners decide transaction order - so a large miner may be able to prevent other users' reporting a consensus fault, and insert a report of their own.

**Comment by wadeAlexC** [comment]
One last thought, I wonder if it'd be useful to impose a minimum fault age larger than "1 epoch." 1-epoch-old-faults feel to me to be most likely to be submitted by the miner themselves.

With a minimum fault age of, say, 1 deadline, there's more room for others to observe and report the consensus fault - and hopefully a lower chance that a miner can report themselves.

**Comment by wadeAlexC** [comment]
One more last thought, maybe there shouldn't even be a reporter reward. Existing miners are incentivized to report consensus faults because it raises their chance of getting elected for block production.

The reward seems too gameable.

**Comment by anorth** [comment]
cc @zixuanzh

**Comment by anorth** [comment]
Ok, for now we'll implement a simple thing. We can do something more complicated if research determines it's necessary later.

- Require the fault epoch (which is the higher of the two blocks epochs) to be >= `ConsensusFaultElapsed`

This has the same effect as @wadealexc's suggestion. It allows an arbitrarily old fault to be reported once, but after that, only a fault committed subsequent to the previous reported fault. Since a miner is ineligible for election while serving a fault penalty (finality epochs), we don't expect them to be capable of producing another one during that period.

If we're unhappy with the inability to proportionately penalise a number of ~simultaneous faults, we could increase the penalty for each report.

**Comment by wadeAlexC** [comment]
I think it should be strictly greater-than - but SGTM otherwise.
