### ISSUE TITLE
MaxPreCommitRandomnessLookback and MaxProveCommitDuration

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1012]
These constants need to be reduced from 10000.  Needs sync between @whyrusleeping and @nicola.

We can support different numbers for different sector sizes.

**Comment by anorth** [comment]
Some background discussion in #878. Some decisions to be made include:
- whether `MaxProveCommitDuration` includes `PreCommitChallengeDelay`, or that must be added
- different values for different sector sizes

**Comment by nicola** [comment]
`MaxProveCommitDuration` must include `PreCommitChallengeDelay`

**Comment by nicola** [comment]
Ask @placer14 what numbers he has seen via sentinel.

**Comment by anorth** [comment]
@whyrusleeping suggests:
- MaxPreCommitRandomnessLookback at least a day, but the 10000 seems fine
- MaxProveCommitDuration want to consult with @nicola; since the penalty is so high, don't want operational hiccup to cause this. Want it to be much greater than the SNARK time, e.g. 24hr.

Let's put those numbers in now, and we can tighten them later if it's critical.

**Comment by lucaniz** [comment]
@irenegia and I were proposing to take   `MaxPreCommitRandomnessLookback` = max{MaSealDuration, finality} in [#263 ](https://github.com/filecoin-project/research-private/issues/263#issuecomment-673396167). 

According to @nicola's numbers in [#878](https://github.com/filecoin-project/specs-actors/pull/878#issuecomment-674691850), we could take `MaSealDuration`= 24h (for 64 GiB sectors) and then use `MaxPreCommitRandomnessLookback`=24h. 

Since the purpose of `MaxPreCommitRandomnessLookback` is to prevents a miner sealing sectors far in advance of committing them to the chain, thus committing to a particular chain the closer this number is to finality, the better for security.

Wrt `MaxProveCommitDuration`, it seems kind of a lot to set it to 24h, but we don't have particular concerns wrt security.

cc @nicola @irenegia

**Comment by anorth** [comment]
Clarifying what we will implement now:
- `MaxPreCommitRandomnessLookback` = 24h + finality for 64GiB (and 32GiB) (from https://github.com/filecoin-project/specs-actors/pull/878#issuecomment-674691850)
- `MaxProveCommitDuration` = 24hr + `PreCommitChallengeDelay`
