### ISSUE TITLE
CC Upgrade PCD and IP issues

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1021]
There are two potential bugs:

1. The precommit deposit of the new sector is lower bounded by the initial pledge of the old sector.  
- Should there be a precommit lower bound based on the old sector?
- If so should it be the old initial pledge, which is greater than or equal to precommit deposit?

2. The initial pledge of the new sector is not impacted by the old sector
- I think it should be lower bounded by the old sector's pledge 
- We'll need to add a field to `SectorPreCommitOnChainInfo` to do this

There is also an underspecification we should think through:

1. If you precommit many sectors as upgrading from one old sector all sectors will be added but only one will really "take the place of the old sector" since only the single old sector will expire.  Should all new sectors inherit constraints from the old sector.  Currently all such sectors will have termination fees impacted by the old sector's age and BR.  After this issue they will probably all have initial pledges lower bounded by the old sector's initial pledge.  Should only one sector inherit this baggage or are we ok giving it to all sectors.

**Comment by anorth** [comment]
1. No, there should be no bound on PCD
2. The IP of the new sector should be lower-bounded by the one it's replacing

We probably made these errors through the path of initially setting PCD equal to IP, and then breaking that equivalence again.

It's ok, but not great, that if many sectors attempt to upgrade the one CC sector, they all inherit the minimum IP (and higher termination fee). If it's easily avoidable in `ConfirmSectorProofsValid`, let's try. From a quick reading, I think we can detect if if the same sector is upgraded twice _in the same epoch_, but not otherwise. This is an avoidable situation for the miner.
