### ISSUE TITLE
Swapping a signer in `MultiSigActor` allows for a signer to approve a transaction one more time

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1041]
### Description

A MultiSigActor allows the signers (if they agree) to swap a signer’s address for another address.

The addresses are not modified for pending transactions. Hence, if there is an existing transaction which has the
user’s first address in the Approved array. They may call Approve() again after the address has been swapped
which will add the new address to Approved.

A signer may repeat this process multiple times giving them the potential to be the only signer for a transaction
if their SwapSigner() transactions are approved.

### Recommendations

Consider iterating through existing PendingTransactions and swapping the addresses or otherwise prevent
the double approving of a transaction.

## Notes
Concrete example: A, B, C have a 3/3 multisig.  A wants to approve Tx.  A proposes and approves Tx.  A proposes swapping A for A'.  B and C approve swap.  A' approves Tx. A' proposes swapping A' for A''.  B and C approve swap.  A'' approves Tx.  With 3 approvals Tx is executed even though B and C never approved.

Can we implement the recommendation given desired performance and gas targets for a multisig user?  What is the expected size of concurrent pending transactions? Does it not matter because the swapping party pays the burden of the gas covering security?  Feels like recommendation has acceptable trade offs -- swapping should be relatively rare.  If we accept the tradeoff then iterating and swapping should be an easy fix.

No action alternative is to communicate the security policy that approvers of SwapAddress must not sign off on swap and consider the operation safe until all transactions containing previous address are canceled (requires cooperation of all proposers so possibly all addresses in multisig which constrains secure behavior)

**Comment by anorth** [comment]
This behaviour is only a problem if one considers the semantics of swapping addresses as changing the identifier for a single off-chain entity (think: key rotation), rather than changing which entities are signer (think: board member rotation).

The latter behaviour can also be achieved with an add/remove or remove/add sequence, though each of those must pass through as state where the approving fraction of signers is changed from the ideal.

Note that when signers are removed generally we don't go around trying revoking their approval of pending transactions. Also of note: transactions proposed by parties which are removed as signers become un-cancellable, which is a problem for:

> until all transactions containing previous address are canceled (requires cooperation of all proposers so possibly all addresses in multisig which constrains secure behavior)

So I think this comes down to a design question. Do we want to explicitly support a key rotation mechanism that prevents the rotating party from approving twice, without requiring workaround behaviour of clearing out pending transactions (which may be impossible). This will constrain entity rotation to use an add/remove sequence instead.

**Comment by anorth** [comment]
Note from @whyrusleeping :
- Does think of it as swapping entities
- But when removing a signer, consider their votes void anyway
- Prefer to remove all votes from removed signers (in RemoveSigner too)
- Swap is just an add + remove
