### ISSUE TITLE
Payment channel can reduce payee claimable funds

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#1046]
The payee’s(receiver of funds) balance is stored in the state variable `ToSend`. The `ToSend` amount is the total received from all lanes.

During a lane merge, the amount redeemed from other lanes is summed into `redeemedFromOthers` and the amount to be redeemed from the current lane is `ls.Redeemed`.

The line below takes the current amount to be redeemed, less the amounts already redeemed across all merged
lanes. There is no guarantee that `balanceDelta` is greater than zero.

```balanceDelta := big .Sub(sv. Amount , big . Add ( redeemedFromOthers , ls. Redeemed ) )```

If `newSendBalance := big.Add(st.ToSend, balanceDelta)` is greater than or equal to zero, the function will not revert.

That is if `ToSend >= balanceDelta`, it will set `st.ToSend = newSendBalance` which would reduce the `ToSend` value.

**Comment by dirkmc** [comment]
My understanding of lane merging is that the payee may want to accept a voucher that decreases claimable funds, as a way of splitting the gas cost with the payer.

For example if the payee has two vouchers worth 4 FIL and 5 FIL, and it costs 1 FIL in gas to submit each voucher, the total that the payee will receive after submitting both vouchers is (4 - 1) + (5 - 1) = 7 FIL.

So the payee asks the payer for a new merge voucher worth 8.5 FIL. The payer agrees (because they will now spend 8.5 FIL instead of 4 + 5 = 9 FIL) and sends the merge voucher. The payee submits the single merge voucher and receives 8.5 - 1 = 7.5 FIL.

**Comment by ZenGround0** [comment]
@whyrusleeping as the designer of multilane payment channels is this an intended feature or a bug?

Since both parties need to consent to the voucher the worst that can happen is that users can be tricked into agreeing to a bad deal.  This seems like it could easily be fixed by a non-protocol-breaking change to user facing code.  However if it is slightly better to change the behavior to disallow this it should only be a 1-3 line assert that the voucher doesn't have a negative delta, which will be so easy we should just do it now since we're already thinking about it.

**Comment by ZenGround0** [comment]
Here's a related issue that seems worse.  It has to do with merging back into a lane that has previously been merged into.

Imagine there is a payment channel with 1000 FIL and three lanes. All lanes (1, 2, 3) have nonce 1 and redeemed 100 FIL as recorded in state.  Then there is a voucher with amount 300 merging lanes 1 and 2 into lane 3 and bumping nonces to 2.  It shouldn't add any value since 300 covers the balance of all lanes.  Now lane 1 and 2 have balance 100 and lane 3 has balance 300.

Now say we have a transaction that merges lane 3 back into lane 1.  If we bump the nonces one more time to 3 on lane 1 and lane 3.this should be allowed.  `balanceDelta := big.Sub(sv.Amount, big.Add(redeemedFromOthers, laneState.Redeemed))`, which in this case would be `sv.Amount - 100 - 300`.  This double counts the 100 from lane 1.  So the voucher `sv.Amount` would need to be 100+ the actual amount you want to keep in the lane state.  If you wanted to move lane 1 to 300 you would need to provide 400 amount.

My guess is that lane merge is practically only done in one direction and since no one wants to do this it hasn't been seen as a problem.  However it's weird that the on chain model allows for it.  And like the original issue it might be possible to confuse someone into getting into a bad agreement if they aren't checking their work thoroughly.

**Comment by ZenGround0** [comment]
@anorth the original issue is called out as a feature in the paych spec 

in [Lanes](https://filecoin-1.gitbook.io/spec/content/systems/filecoin_token/payment_channels/_index#lanes)
> As an incentive for the channel sender to accept the merge lane request, the channel recipient can ask for a lower total value to balance out the gas cost. For instance, if the recipient has collected vouchers worth of 10 FIL from two lanes, say 5 from each, and the gas cost of submitting the vouchers for these funds is 2, then it can ask for 9 from the creator if the latter accepts to merge the two lanes. This way, the channel sender pays less overall for the services it received and the channel recipient pays less gas cost to submit the voucher for the services they provided.

which mirrors @dirkmc's point above about this explicit issue
