### ISSUE TITLE
When proposing internal method calls on multisigs, ID address must be used

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs-actors#1168]
I attempted to use a stable address in a call to an internal multisig method (via propose). When it executed, i got an exit code 8, which implies the caller check failed. I think this is because it checked the ID address against the actor address and failed out.

If this is true, we should probably normalize these down at runtime.

**Comment by anorth** [comment]
To clarify: you proposed a transaction with `To` being the stable address of the multisig actor itself? Which method was it?

The multisig does normalize all externally-provided addresses (I think even on the v0.9 branch). It does not attempt to normalize `rt.Receiver()` or `rt.Caller()` though because the VM is supposed to only provide already-normalized addresses (otherwise actors would have to do a lot more normalization calls).  

> 	// Can only be called by the multisig wallet itself.
>	rt.ValidateImmediateCallerIs(rt.Receiver())

It sounds like you ran into https://github.com/filecoin-project/lotus/pull/3589, which I desperately hope will be fixed with the next upgrade.

**Comment by anorth** [comment]
https://github.com/filecoin-project/lotus/pull/3589 has landed, please lmk if you have trouble even after that.
