### ISSUE TITLE
How to calculate gasUsed of precommitsector？is there any doc about it ?

### ISSUE THREAD

**Issue by hsn999** [filecoin-project/specs-actors#1386]

**Comment by ZenGround0** [comment]
@hsn999 if you are trying to estimate the expected gas usage of precommit sector as a miner operator this question should be asked in the lotus repo.  In principle this is a straightforward operation to estimate. Since it should deterministically depend only on state that you control I wouldn't expect gas usage to differ at all from estimation. But I don't know the lotus command to do this estimation.

If you are asking how to calculate the gas usage of a message already on chain you can look at the receipt data using lotus or an online block explorer.
