### ISSUE TITLE
Why miner_state PreCommittedSectors & Sectors use different data structure?

### ISSUE THREAD

**Issue by GFZRZK** [filecoin-project/specs-actors#1395]
I don't think `PreCommittedSectors` need hamt. If uses amt, `state` can also work and can save disk store and CPU resource. Can you explain why here need a hamt and `sectors` not?

**Comment by Stebalien** [comment]
AMTs are efficient when the keys are contiguous and start at 0. I.e., when the data is something you might store in an array. The height of an AMT is `O(log(max_element))`, regardless of how many elements it has, and a sparse AMT can easily have many tiny, poorly packed objects.

- `PreCommittedSectors` tends to have very few elements, sometimes sparse, at some offset (the highest allocated sector number). Using an AMT would make it much deeper than necessary.
- `Sectors` is usually tightly packed and sequential. Even if a miner chooses to allocate ranges of sectors instead of simply starting at zero, the tight packing allows sectors to be stored next to each other.

As the network evolves and sectors expire, it might make sense to change the type for `Sectors` to better accommodate an initial sector number offset and "holes". There's also an outstanding TODO to improve the AMT type to reduce/remove some of these limitations. But, given its sparse nature, `PreCommittedSectors` will likely always be an AMT.
