### ISSUE TITLE
Investigate increasing aggregation limit from 200 --> 400 sectors

### ISSUE THREAD

**Issue by momack2** [filecoin-project/specs-actors#1400]
As per https://github.com/filecoin-project/specs-actors/issues/1257 we're working to unblock aggregating up to ~200 sectors for both large and small miners. What changes would be required to bump that number from ~200-->400? (Ex, increasing precommit lifetime by another x days?)

@ZenGround0 - can you sync with @nicola and @zixuanzh to investigate?

**Comment by ZenGround0** [comment]
@nicola it would be good to get a confirmation that there are no security consequences to increasing `MaxProveCommitDuration` from a week to a month and a half.

fyi @anorth in case you foresee any other issues with making `MaxProveCommitDuration` much larger since I believe you were involved in setting this parameter.

**Comment by anorth** [comment]
Thanks, my primary concern is that @nicola and team fully understand and 👍 .

**Comment by momack2** [comment]
To make sure I understand - adjusting the provecommit window also flows into extending sector expiration to ensure the shortest sectors are still ~6 mo, so if you have a 24 day prove commit your total sector lifetime actually needs to be proportionally longer?

**Comment by ZenGround0** [comment]
I think we are aligned.  To get concrete a miner can currently set expiration to a minimum of 6 months and 150 epochs from precommit epoch.  With the current FIP 0013 changes this will become 6 months and 6 days from precommit epoch.  To support aggregates of ~400 with max fairness this becomes 6 months and 24 days from precommit epoch etc.

Something to highlight is that his impacts all miners sealing sectors between 6 months and 6 months + new MaxProveCommitExtension, even those that do not change their workflow and continue to use the existing single sector precommit and prove commit methods.

**Comment by ZenGround0** [comment]
Thinking about this more there is a third strategy that is less good but that we should use over strategy 2 above if it turns out the extended effective sector minimum is not ok:

### Move sector minimum check to prove commit time

Instead of checking at precommit time that the sector expiration is valid we can do only basic validation in precommit to make sure nothing is wildly off and then push the more precise expiration validation to prove commit time.  

This is good because miners that prove commit soon after precommit won't need to inflate their expiration time by the new days long MaxProveCommitExtension.

This is bad because any miner making use of the change by trying to use less than 6 months + new MaxProveCommitExtension for their expiration will be racing against the chain to try to time ProveCommit messages.  And they could lose this race and suffer expensive errors.  It's also a more complicated change and will probably lead to lotus integration gotchas that would be better to avoid.

## Recommendation

In case it's not obvious I'm in favor of solution 2: increasing MaxAggregateSize and MaxProveCommitDuration.  The only reason not to do this is if the community has a strong negative opinion on the effective min sector expiration that this change causes.

**Comment by kidcdf** [comment]
cool

**Comment by momack2** [comment]
Agree that we should do solution 2 (not a more complicated and error prone alternative). 

I'd propose setting `MaxProveCommitDuration` to either 14 or 30 because they are convenient timeframes to think about for a miner (2 weeks, or 1 month window). For the latter option - do we know whether small miners would ever choose the longer window and forego the benefits of onboarding capacity faster (and getting the realtime incremental increase in blocks won) in order to get the relatively small gas savings from bundling more PoReps together? If it isn't going to be used, it's not worthwhile to push out all 6mo sector lifetimes by a month (but willing to do that if this is advantageous/appealing to small miners!)

**Comment by momack2** [comment]
(getting some 👍 over slack for having the option to wait in order to minimize gas fees)

**Comment by momack2** [comment]
I believe the final decision is to set aggregation limit to **800**, and increase the MaxProveCommitDuration to **30 days** so small miners can take advantage. Shall we close this @ZenGround0?

**Comment by f8-ptrk** [comment]
30/6 = 5

**Comment by arajasek** [comment]
Finalized in https://github.com/filecoin-project/FIPs/pull/100
