### ISSUE TITLE
State migration for/after SnapDeals implementation

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/specs-actors#1514]
@ZenGround0 will more details for this issue, like we discussed on planning meeting for SnapDeals

**Comment by ZenGround0** [comment]
## Description
SnapDeals introduces some changes to miner state.  Most notably a new field to the sector info and a new filed to the deadline.  We need a migration included in the upgrade to actors v7 to make this transition possible.  We will be transforming the bulk of growing chain data during this operation which will require implementing migrations at a much higher scale than we've seen before since we haven't migrated sector info data in a year and we've added metadata covering an additional ~10EiB since then.

## Done Criteria
* We have a migration that 1) moves v6 sector info data into v7 sector info to account for new sector info key 2) moves v6 deadline data to v7 deadline to account for new sectors snapshot field

## Dependencies
- Finish dispute window post fix: https://github.com/filecoin-project/specs-actors/issues/1521
- Finish up the new sector info format with sector key: https://github.com/filecoin-project/specs-actors/issues/1530
- Prepare our migration tools for lots of data: https://github.com/filecoin-project/specs-actors/issues/1460

## Ongoing work

No work in progress

**Comment by arajasek** [comment]
Gonna write up the vanilla migration to enable testing on Lotus, something far more intelligent will be needed though (as noted above)

**Comment by arajasek** [comment]
Closed in #1532
