### ISSUE TITLE
Implement missing part of registered proofs and ProofRegistry

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/specs-actors#190]
It seems that the facilities to handle different proof versions and the fixed registry have not been ported over: https://github.com/filecoin-project/specs/search?q=proofregistry&unscoped_q=proofregistry

Specifically there needs to be a list of valid RegisteredProofs, indexed by block height, and submission of proofs needs to verify that it is valid for this given height. This needs to to happen for both PoRep and PoSt

The only valid proof version is currently `StackedDRGV132GiB{Seal|Post}`. All other proofs must not be allowed in non dev networks.

cc @sternhenri

**Comment by sternhenri** [comment]
For now, we can use 48 hours (in epochs) as the `MaxSealDuration` for `StackedDRGV132GiBSeal`. We will get tighter bounds but this should be a sufficient approximation for Painnet.

**Comment by anorth** [comment]
I am not convinced the full versioned registry should appear in the actor code (at the moment, anyway), though if only some proof types are valid, perhaps there should be a list of valid ones.

The registry can live entirely outside of the state machine. When a verification syscall is made, the epoch number is known and can be passed to the proofs library. The registry can thus be maintained entirely within that library. When the actor code was disentangled from the rest of the spec, the actors contained no reference to the proofs registry so it wasn't brought along. All the actor code needed was an integer to plumb from one call to the next. @porcuquine I think you added the registry to the spec - was it an oversight that the actors didn't use it, or intended because it would live outside the state machine?

The (off-chain) registry can then be versioned just like other non-state-machine protocol changes (and outside the scope of this repo).

Alternatively, if someone wants to declare a design decision that the registry should exist here, then this is the *only* place it should exist. In that case I don't think it would take the form of a table as suggested. We haven't addressed versioning of the actor code in this repo yet, but it's quite likely to take the form of vendoring the entire actor set, rather than a proliferation of tables and switches throughout the code.

**Comment by porcuquine** [comment]
I put the registry inside of filproofs to emphasize that proofs needs access to the internal details of the registered proofs. I didn't want to make a strong statement that any other part of the system requires it.

Independent of the registry, there needs to be some mapping which allows nodes to determine whether a given proof (if verified correct by filproofs) should be considered meaningful at the epoch in question. I think this needs to be part of the state machine (but maybe I'm wrong). It needs to be part of a check which happens *before* proof verifying functions are called. A valid proof of an invalid RegisteredProof (for the epoch in which it appears) can be treated like a failed verification on the spot.

To summarize what I think I've said:
- Proof Registry belongs in proofs.
- A mapping from Epoch to a set of allowed RegisteredProofs belongs elsewhere (probably in the state machine, right? I don't feel strongly about where it 'should' be apart from it needing to serve the function described above.)

Relatedly, but not identically, miners will need to generate their proofs with the right RegisteredProof for the epoch in which they perform them. The logic for determining that probably *doesn't* need to live with the actors. However, it probably *does* make sense to have a single source of truth for this, so if verification requires this information to live in the state machine, then it may make sense to call into that functionality from outside when miners need to make related decisions.

**Comment by porcuquine** [comment]
Addendum: while it is true that the registry itself could also contain epoch-validity information, that would require proofs to know about epochs and to be coupled with a meta-concern outside its scope. I think there are two logical structures and they belong in logically different places. If the non-proofs structure needs more meta-data (like sector sizes), it can either duplicate it out of band, or we can add an API call for retrieving it from the registry.

**Comment by anorth** [comment]
See also #385

**Comment by anorth** [comment]
I'm closing this for now because there's no concrete action to be taken yet. It might be more clear when we have an actual upgrade to do. But in any case that will require an update to the actor code itself, so we can make changes then.

See #385
