### ISSUE TITLE
Market actor VerifyDealsOnSectorProveCommit validation

### ISSUE THREAD

**Issue by austinabell** [filecoin-project/specs-actors#280]
Issue opened as more of a question. I noticed in this function call there is some subtraction that could potentially be negative and seems unchecked [here](https://github.com/filecoin-project/specs-actors/blob/e569f4a2f50403eeaef22c410d36d2ed30c57e37/actors/builtin/market/market_actor.go#L273) 

Seems someone could have the SectorExpiry parameter be less than or equal to the current epoch and the function call could still execute? Also if there is no validation that the DealIDs are not an empty list, which also causes inefficiency and potentially a bug.

There is some related validation for each deal in `validateDealCanActivate` and that verifies `currEpoch <= dealProposalStart` and `SectorExpiry > dealProposalEnd` but relies on the validation in other calls. I do see that if there are no deals the numerator of that division is 0 so this negative value doesn't matter, but if the `rt.CurrEpoch == params.SectorExpiry` then there will be a divide by 0. Also, it means you are doing extra bs read(s)/write in your case if either one of these checks fails.

To be clear this issue is just a suggestion to validate `params.DealIDs` are not empty and/or `rt.CurrEpoch < params.SectorExpiry` at the start of this function to avoid extra computation/ blockstore reads and writes, and possibly avoid a division by 0 which is an unnecessary panic.

**Comment by anorth** [comment]
@aarshkshah1992 could you please review and comment here, and propose a PR if you think we should change something.

**Comment by aarshkshah1992** [comment]
The function and calculation referenced in the issue does not exist anymore. 
We do now have a `ValidateDealsForActivation` function that simply returns a combined weight of zero if no deals exist.
We have also changed the logic to calculate deal weight as:

```
        dealDuration := big.NewInt(int64(proposal.Duration()))
	dealSize := big.NewIntUnsigned(uint64(proposal.PieceSize))
	dealSpaceTime := big.Mul(dealDuration, dealSize)
	return dealSpaceTime
```

Since we mandate that the deal end epoch be greater than start epoch and that PieceSize is always positive when we publish a deal, the weight will always be positive.

@anorth This issue does not exist anymore and be closed.
