### ISSUE TITLE
Fix reward actor technical debt

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#317]
The reward actor is not ready for prime time.

- No checks that the actor's actual balance is compatible with the reward schedule
- In case of a null round, the reward paid out will be the reward corresponding to the null epoch, not for an actually mined epoch.
- semi-done: No documentation of high level intent or what any of the state variables mean or functions do

- ~No tests~
- ~Initial state should reflect genesis configuration, not zeros (#374)~
- ~Logic doesn't handle being called more than once each round (multiple blocks)~
- ~Logic doesn't handle not being called every round (for null tipsets), undercounts~
- ~Doesn't divide by expected number of leaders when computing reward for a miner~
- ~The `Simple/BaselineSupply` state variables account for expected reward, not actual reward paid; money supply will always be an overestimate~
- ~Total allocation values hardcoded as constants, which are wrong; should be inferred from actual balance~

- ~`BlockTimeSeconds` duplicated and inconsistent with miner actor~
- ~`Lambda` parameters totally opaque and undocumented~
- ~Uninitialized `LastPerEpochReward` state~
- ~Unused argument in ConstructState~
- ~Unused `TicketCount` in `AwardBlockRewardParams` should be removed~

**Comment by anorth** [comment]
FYI @Kubuxu

**Comment by anorth** [comment]
Merging #329 into this:
> Existing code does an inverse mapping of realizedCumsum to effectiveNetworkTime but the integer math is always returning zero unless the daily power exceeds the baseline. This is not the intention and we should introduce a notion of precision here. If baseline is 100PiB on the first day and only 50PiB shows up, network time advances by half a day.

**Comment by anorth** [comment]
Thanks for your great work here @Kubuxu.

I'd be happy to close this issue after:
- Add checks that the actor's actual balance is compatible with the reward schedule
- Document in-code the fact that "In case of a null round, the reward paid out will be the reward corresponding to the null epoch, not for an actually mined epoch." and why that's the case

@ZenGround0 would you mind making those final tweaks for us?

**Comment by ZenGround0** [comment]
> Document in-code the fact that "In case of a null round, the reward paid out will be the reward corresponding to the null epoch, not for an actually mined epoch." and why that's the case

Is this currently the case?  It is phrased as if this is done already but I see `UpdateNetworkKPI` doing the null round updates.  Since this method is only called during cron it should be running *after* a tipset's worth of rewards have been paid out.  The comment above this function also indicates that we are not doing what is prescribed in this issue: "This is only invoked for non-empty tipsets.  The impact of this is that block rewards are paid out over schedule defined by non-empty tipsets, not by elapsed time/epochs."

> Add checks that the actor's actual balance is compatible with the reward schedule

Since we already do an assert during `AwardBlockReward` I'm guessing this is asking for us to return an error as part of running `UpdateNetworkKPI` if the updated award amount is greater than the actor balance.  Is that right?

**Comment by anorth** [comment]
The schedule of pay-out is fixed compared with when this issue is written. Reward due in a null round is not paid, but the schedule of future rewards is not affected by that. The comment about the schedule has rotted, please remove it.

Because cron runs at the end of epochs, in a sequence of epochs `1000, 1001(null), 1002`, at the end of 1000 the reward for 1001 is calculated. It is never used and not recalculated at the end of 1001, and so the reward for 1001  is paid in epoch 1002 (and then the reward for 1003 is calculated). This seems like not a catastrophe, and resolvable if we get cron on null epochs.

**Comment by anorth** [comment]
I think the assert in `AwardBlockReward` needs to be replaced with a `big.Min()` or similar so that it doesn't kill the chain, just stops paying.

**Comment by ZenGround0** [comment]
> Because cron runs at the end of epochs, in a sequence of epochs 1000, 1001(null), 1002, at the end of 1000 the reward for 1001 is calculated. It is never used and not recalculated at the end of 1001, and so the reward for 1001 is paid in epoch 1002

I get it now.  I had thought the issue was describing the inverse of this: 1002's reward being calculated by processing the previous null block at 1001.

> This seems like not a catastrophe, and resolvable if we get cron on null epochs.

Would it be better to do it the other way, computing first non-null by calculating reward at previous null epoch?  Draft #669 is fairly simple and is maybe ~40% of the way there.  Do we expect null-epoch-cron with high enough probability that we don't want to waste work it would take away from us?
