### ISSUE TITLE
PublishStorageDeals on Storage Market Actor should reject deals that are already published

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/specs-actors#364]
If a client sends a deal proposal to a miner, and signs the deal proposal with their signature, then sends the data for the piece to the miner, what prevents the miner from submitting the proposal to the chain lots of times, storing it, and getting paid multiple times for it? (other than the total escrow a client has in the SMA)

I believe answer to that question at the moment is nothing.

In thinking through possible solutions to the problem, there are two issues that I believe need to be solved:
1. Deal proposals are not unique as long as they are for the same pieceCID, start epoch, end epoch etc
2. Even if we added some unique identifier to them I'm not clear how you could query the existing deals to see if a proposal was unique in a way that is performant.

Maybe there is a different approach I am not thinking of?

**Comment by hannahhoward** [comment]
Alternate idea:
SMA can issue deal submissions authorizations based on a client's signature.
These are a kind of delegated authorization to submit a deal, and when a client proposes a deal to a provider, rather than their signature being enough to validate it, it also needs to contain an unexpired unused authorization?

**Comment by whyrusleeping** [comment]
This one is tricky, but I think we can make it work by indexing the deal states by the proposal CID, and adding the deal ID to the deal state. This means that now getting the deal state from the deal ID *requires* an extra hamt lookup, but most of the time we're doing that anyways.

We can then add a nonce to the deal to make it possible for clients to make the same deal with the same miner multiple times (not sure why they would want to... maybe we don't need this?)

Then, the only thing we have to do is make sure that deals remain on chain at least until their state date, which means that attempting to resubmit the deal will fail because its past the deals start date.

**Comment by anorth** [comment]
A deal proposal is a lot larger than a deal state, but immutable, so avoiding decoding of it in order to get to deal state would be significant.

An observation: we only need to detect duplicate deal proposals up until the proposal's start epoch, because after that it can't be sealed into a new sector anyway. But most deal proposals and states will presumably live for much longer than that. AFAICT, the proposal must stay in chain state until the deal ends (or expires un-sealed), b/c the proposal information is not duplicated into the deal state object.

So perhaps we could have a PendingProposals HAMT keyed by proposal CID that only contains proposals that have not yet reached their start epoch, and is only for duplicate detection. We remove from this collection when the deal is committed or expired. All proposals will reach one of these states, with cron eventually catching the expired proposals.

**Comment by whyrusleeping** [comment]
My main concern about having an extra hamt here is just the added state churn it causes. I'll go ahead and implement it for now, and if it ends up being really disruptive, we can try to optimize from there
