### ISSUE TITLE
Implement Window PoSt "skipped" faults

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#410]
A follow-on from the initial Window PoSt implementation is to implement handling of faults that are declared concurrently with a PoSt submission. Such faults pay the same per-sector penalty as if the fault was undeclared and the PoSt missed, but allow the PoSt for other sectors in the same partition to succeed.

If we don't do this, then when a miner fails to declare a single sector fault in a partition before the cutoff, the whole partition is penalised.

**Comment by acruikshank** [comment]
The basic use case is straightforward. Here are some questions and what I plan to implement until they're answered (possibly in PR).

1. Should skipped sectors that are recoveries will be removed from recoveries? I'll assume yes.
2. Do we need to charge retracted recoveries separately? Currently a skipped fault and a failed recovery are both charged SP, so I'll charge all skipped faults SP.
3. What happens if you attempt to skip a sector that is not due at this deadline? I'm going accept it as a fault and charge SP, so miners will be penalized for this mistake, but not lose their whole PoSt.
4. Question: What if a skipped fault is already a fault? I'm going to just ignore these (with no penalty) unless there's a reason not to.

**Comment by anorth** [comment]
1. Yes
2. It's unfortunate, but I think we have to charge SP, yes. Please leave a comment in the code asking the question whether we could avoid penalising them further (as for declared faults). You must not deduct power again though.
3. I have a hunch that future changes will force us to only be able to process things due at the deadline, so reject the PoSt now.
4. Ok


@nicola if a miner declares a recovery, and then last-minute declares it a skipped fault, must they pay SP? In contrast, if a miner declares recovery and then declares a fault before the fault cutoff, we don't charge anything extra.

**Comment by nicola** [comment]
Today:
- Recovery -> Skipped Fault = SP
- Recovery -> DeclareFault -> Skipped = no fee

The two cases are documented here: https://observablehq.com/d/640c2bc9b55456f7#sectorRecovery
