### ISSUE TITLE
Implement pre-commit deposit calculation and rollover to pledge

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#424]
The pre-commit deposit is currently a stub, always zero.

The deposit should be equal to the initial pledge for the sector (#468). This initial pledge value should be calculated and stored in the pre-commit state. The initial pledge does not need to be recomputed when the proof is verified. Instead, the precommit deposit should be rolled directly into the locked pledge funds.

Since the precommit deposit value is already stored in the state, the most straightforward thing might be to rename `precommit.PreCommitDeposit` to `precommit.InitialPledge`, and simply treat it as a deposit during the precommit phase.

**Comment by anorth** [comment]
Consider doing #419 first.

**Comment by acruikshank** [comment]
@anorth There might an issue computing initial pledge on precommit. `IP=20*BR(t)` and BR depends on QA weight of the sector. It's not clear QA weight is fully defined prior to prove commit. We only lock QA weight into the SectorOnChainInfo at prove commit. The market actor computes the weight and marks deals active at the same time, so we currently don't have a means to compute QA weight prior to prove commit.

The block reward and total storage power are also a function of time, so there really can be no guarantees about pre-commit deposit equaling initial pledge unless we define initial pledge to equal the pre-commit deposit.

If we are confident that deals must be published prior to precommit (so QA weight cannot change between pre- and prove- commit) we can add the ability to compute QA power without altering state.

Otherwise we can compute an upper bound on QA weight based on sector size, but this will make precommit deposit >= initial pledge.

Thoughts?

**Comment by acruikshank** [comment]
Note that the above assumes #468 the existing initial pledge calculation can be implemented this way easily.

**Comment by acruikshank** [comment]
A conversation with cryptoecon suggests that we'd rather compute the initial pledge at precommit time than deal with inconsistencies between precommit deposit and initial pledge. Since initial pledge correlates to activation time of the sector, we'll use the longest possible duration between precommit and commit to perform the calculation to compute the worst case value for pledge.

Plan approved by @zixuanzh:

> My preference would be to
1. Split VerifyDealsOnSectorProveCommit into two functions. One that computes deal weight based on a minimum activation epoch and another that actually activates the deals at prove commit.
2. Compute deal weight at precommit, use it to compute initial pledge with assuming a worst case activation time. Use this initial pledge as the precommit deposit.
3. On prove commit, transfer precommit deposit to lock funds as the initial pledge. Activate all deals.

**Comment by anorth** [comment]
Sounds good, thanks.

To confirm:
- we are defining the initial pledge to be calculated at PreCommit time
- we are defining the pre-commit deposit to be that initial pledge

We could, optionally, recompute the pledge at ProveCommit time, for the purpose of reducing it. Since we have to traverse all the deals anyway to activate them, this might not cost anything extra. But let's not do it for now, anyway.

**Comment by anorth** [comment]
Note from #485, which I am implementing now:
- If the new sector is replacing an already-proved committed-capacity sector, the new sector's pledge must be at least that of the sector it is replacing.

**Comment by anorth** [comment]
@acruikshank identified that despite computing initial pledge in pre-commit, we might need to re-process the deal weight to compute the sector's power in prove-commit, with the now-known activation epoch. But this would make the pledge higher than the power would otherwise imply.

I talked with @zixuanzh and we resolved:
- a sector's initial pledge should match the power the sector represents, we should use the same calculation inputs for both
- we should calculate power too at pre-commit and make it consistent with the initial pledge (tho the power won't take effect until prove-commit)
- taking the latest possible activation epoch would overestimate the sector's power, so rather than do that, use the pre-commit epoch for sector quality for both power and pledge calculations; the pledge secures the power

In implementation, I think this means calculating and storing the deal weights in the pre-commit info, to re-use at prove-commit.

We noted that since the deal weights are stored in state only for use in sector quality calculation we could just store the sector quality to be more space-efficient. But don't do that yet - preserve flexibility to alter the quality computation without a giant state migration.
