### ISSUE TITLE
Miner actor MinerInfo#PeerID filed should be a byte array

### ISSUE THREAD

**Issue by frrist** [filecoin-project/specs-actors#425]
Spawned from a conversation on [slack](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1591222055359400?thread_ts=1591221924.359100&cid=CHMNDCK9P) --`MinerInfo#PeerID` should be a byte array, this removes the dependency on `github.com/libp2p/go-libp2p-core/peer`.

**Comment by anorth** [comment]
My motivation for this: the actor code itself doesn't care about the internal structure of this ID. It's just providing discovery for the miner operator so that deal clients can identify the provider off-chain. Yes, we absolutely expect this to be a Peer ID but nothing about the state machine or blockchain is broken if it's not a valid ID. We have no way to validate that the ID corresponds to a real key, an offline miner, etc etc.

But we're pulling in an 8000-line repository of code into a consensus-critical area. While we don't use many (any?) methods of the Peer.ID struct (yet), if we did, any change in their behaviour could constitute a forking change. Our idea of version compatibility differs from the traditional Go versioning approach, "backwards compatible" changes are not compatible for us if they change behaviour _at all_, say to allow or correctly handle something previously disallowed or broken. Go-mod's version handling does not permit this repo to pin a specific version of the libp2p code to enforce compatibility.

When we do versioning for chain upgrades (#385) we'll want to effectively vendor all the actor code, including transitive dependencies. Every dependent repo here represents a potential world of pain.

We should store the peer ID (and addresses, #403) as plain uninterpreted byte arrays and leave the interpretation to off-chain code, which will need to handle various ways it could be invalid anyway. Drop code dependencies on libp2p. This is not a great burden to place on the users.

**Comment by anorth** [comment]
(Dependencies on things like CID have similar potential pain, but are so much more fundamental that the trade-off is much better).
