### ISSUE TITLE
Robustify bulk porep verification to failures

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#431]
There are a few scenarios where a deferred `ConfirmSectorProofsValid` can abort. Some of them I don't think can be avoided.
- Update `ConfirmSectorProofsValid` to handle some possible but irrecoverable errors (like failure to activate deals) without aborting and rolling back state - just drop the provecommit
    - Alternatively, find a way to move all those conditions to `ProveCommitSector`
- Rework the checking of pledge lock-up and precommit deposit so that any funding-related conditions are checked at `ProveCommitSector` and can't halt the `ConfirmSectorProofsValid`
- Change the power actor to defensively allow the callback for an individual miner to fail without aborting processing for all others (which will be irrecoverable), as it does for cron

See discussion on #340.

**Comment by anorth** [comment]
Related to #452

**Comment by ZenGround0** [comment]
I think the code is mostly in a good state already.

> Change the power actor to defensively allow the callback for an individual miner to fail without aborting processing for all others (which will be irrecoverable), as it does for cron

This is already done [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/power/power_actor.go#L390) which I think resolves all critical concerns.

> Update ConfirmSectorProofsValid to handle some possible but irrecoverable errors (like failure to activate deals) without aborting and rolling back state - just drop the provecommit
Alternatively, find a way to move all those conditions to ProveCommitSector

It seems like the current behavior of rolling back state changes is exactly what we want.  `ProveCommit` is stateless on the miner actor, only queuing up prove commit jobs for batching in the power actor.  The power actor clears all jobs success or fail when it is done processing all prove commits.  For power actor and miner actor state it is just like the faulty `ProveCommit` never happened.  Neither actor appears to be left in a bad state so failing this way looks safe.

Doing these checks at cron time instead of during ProveCommit has the benefit of catching any state changes that could happen between the ProveCommit message and the last message processed.  I don't know if there are any examples of a state change that could happen between ProveCommit and Cron that we would need to track if using ProveCommit-time calculations to satisfy requirements at cron time, but keeping the whole thing stateless would keep us from worrying about this whole class of problems.

The worst thing I can see about the current approach is that consumers of chain data will see a successful ProveCommit message but no actual prove committed sector on chain.  This is bad for UX but I think can be addressed at other layers.  Bringing logging to this code will also help on that front.

> Rework the checking of pledge lock-up and precommit deposit so that any funding-related conditions are checked at ProveCommitSector and can't halt the ConfirmSectorProofsValid

For the sake of UX giving miners clear errors during a ProveCommit message seems like a good thing so we might still want to do this.  There is a tradeoff between this UX and the complexity of making ProveCommit stateful.  For example what if ConfirmSectorProofsValid errors somehow but we have already locked up pledge?

One simple way we could catch errors at ProveCommit without worrying about introducing state is to repeat some ConfirmSectorProofsValid checks in ProveCommit.  Going through ConfirmSectorProofsValid we could fail ProveCommit if 
* Precommit doesn't exist (already do this)
* We fail to find precommit Replace Capacity sector or check if it is faulty
* We don't have enough balance to pay for initial pledge

**Comment by anorth** [comment]
> allow the callback for an individual miner to fail

Great. That could do with some clarifying comments about how the miner's state will be unchanged and the provecommits all dropped and not retried, but sounds good.

> current behavior of rolling back state changes

Here the problem is that failure of a single proof causes all of the batch to fail. What I'm seeking there is handling failures related to an individual proof _without_ rolling back all state changes. So `ConfirmSectorProofsValid` would return `Ok` even if some proof failed for an "application-level" reason like a bad deal ID or insufficient funds.

> checking of pledge lock-up and precommit

This was largely resolved already by #424, such that I don't think it's possible to not have enough funds. Please confirm that though.
