### ISSUE TITLE
Prevent sector ID re-use

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#451]
At present, a sector number (sector ID) may be re-used after a sector terminates, either due to missing ProveCommit, or termination. This could open up hard-to-spot error cases, and certainly makes sector number use from the outside very difficult. Re-use is unlikely to be efficient in bitfield-encoding, though there are contrived cases where it could be.

Consider preventing sector number re-use, perhaps by recording a sector number high-water-mark either at PreCommit or ProveCommit, and requiring new pre-commitments to have a higher number.

**Comment by anorth** [comment]
A high-water mark from PreCommit might be too constraining on worker implementations, requiring a strict sequence of precommit calls. But a high-water mark of sectors that have _expired_ would be nearly as simple, and leave much more slack.

**Comment by magik6k** [comment]
There are many cases where we want to partition sector number space into separate ranges, for example:
* Separate range for CC sectors and sectors with deals, so that when we perform CC upgrades we don't 'punch holes' in sector number runs.
* Some miner groups are using custom software which assigns a ranges of sector numbers to worker pools for more efficient scheduling, high-water seems to completely break this model

**Comment by anorth** [comment]
Hmm. Sector ID re-use seems really bad to me the more I think about it. Any other ideas?

**Comment by magik6k** [comment]
The obvious thing that comes to mind is tracking every used SectorID is some persistent state, but that means keeping some data per-sector in un-trimmable state (AMT, Bitfield (probably not because of size constraints), or some specialized set-only ipld bitset) - and with EiBs of churn of sectors per year this will add up to a fair bit of state

Alternatively we could support some way of partitioning the sector ID space by, say, having a separate high-water mark (last-termination based preferably) per 2^32 range of sector numbers

**Comment by nicola** [comment]
Regarding security, I believe that there are some set of parameters for which re-use won't be a problem - we have yet to analyze the protocol on this front. However, avoiding re-usage of sectorID will definitely simplify our analysis and we would endorse it.

**Comment by anorth** [comment]
Noting here that an internal team had assumed sector numbers are unique to a miner. This is a very understandable assumption that many people everywhere will make in building things on Filecoin.

**Comment by anorth** [comment]
@ZenGround0 @acruikshank creative ideas here would be most welcome

**Comment by Stebalien** [comment]
What if we used a bitfield but forced miners to compact it? That is:

* When a new sector ID is first used, mark it in the bitfield. If the bitfield is too large, throw it away.
* Provide a "compact" method where a miner can mark off entire sector ID ranges as "used", freeing up space to allocate new sector IDs.

**Comment by anorth** [comment]
By "throw it away" do you mean "deny the commitment"? 

This idea has a lot of promise. Assuming we raise the bitfield serialized size limit a little, a miner might get at least 1000 contiguous runs to play with (more if the numbers are low-magnitude). For the basic case of starting from zero, compaction of the range (0..N) is equivalent to a high-water mark, but much more flexible.

**Comment by nicola** [comment]
I like that approach (this has to do more with "scale" than with re-use, correct?).

**Comment by Stebalien** [comment]
> By "throw it away" do you mean "deny the commitment"?

I think? I'm not sure what that term means precisely.

**Comment by nicola** [comment]
I expect that that would mean that the message makes it into the block but returns an error (message is not processed).

**Comment by nicola** [comment]
Is there any timeline on confirming sectorID re-usage?

**Comment by Stebalien** [comment]
> I expect that that would mean that the message makes it into the block but returns an error (message is not processed).

Yes. We'd process the message that tries to use the new sector ID, then reject it.

> Is there any timeline on confirming sectorID re-usage?

I assume that means theory is OK with this change?

**Comment by magik6k** [comment]
"Used" bitfield + a 'compact' method works from my side,

**Comment by nicola** [comment]
@Stebalien yes

> avoiding re-usage of sectorID will definitely simplify our analysis and we would endorse it.
