### ISSUE TITLE
Match Deadline abstraction to protocol specification

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#459]
Conversation with @nicola earlier this week brought up an apparent difference between the red team's idea of how deadlines work and specs-actor's abstraction.  Our deadline struct has an `Open` field distinct from the `Challenge` field.  According to @nicola the challenge epoch should be the opening epoch for a deadline, and having both open and challenge is redundant. 

I want to talk to @anorth about the origins, see if we are doing anything with the opening time and then circle back to @nicola to see which is the current understanding of the protocol.  Finally we need to make changes if the current implementation is behind.

**Comment by anorth** [comment]
The code treats `Open` as the earliest time that a PoSt will be accepted. The deadline windows defined by the range `Open` to `Close` do not overlap, but the challenge window for a deadline overlaps with the previous window.

It would be slightly tricker to code to accept a PoSt any time after `Challenge` rather than only after `Open`, but it wouldn't break anything. I would expect @nicola to say the current way is more conservative than necessary, but ok.

**Comment by anorth** [comment]
I have discussed this with @nicola and have decided to leave the abstraction as it is, with non-overlapping deadlines but a challenge lookback.
