### ISSUE TITLE
Process deal slashing immediately when sectors terminate early

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#462]
From builtin/market:OnMinerSectorsTerminate:
```
// Note: we do not perform the balance transfers here, but rather simply record the flag
// to indicate that processDealSlashed should be called when the deferred state computation
// is performed. // TODO: Do that here

```

**Comment by aarshkshah1992** [comment]
@anorth Please update the labels when you can.

**Comment by anorth** [comment]
This awkward flow where the deal is marked for slashing, rather than processed on the spot, is probably just leftover from when the deal incremental processing was re-done.

It's introduced a bug because the code never checks whether or not the deal had in fact ended naturally before the sector was terminated - the collateral is slashed regardless.

Restructure this to process the slashing immediately in `OnMinerSectorsTerminate`. This will likely remove all slashing from `updatePendingDealState`. There's an open question whether to process the remaining deal payment and delete the deal from state (in which case the deferred state update will need to handle the deal being gone), or mark the deal to be removed from state after the deferred update processes the final payment. The second way is probably easier.

**Comment by aarshkshah1992** [comment]
We don't slash deals that have expired anymore and leave the task of cleaning expired deals to the Cron Tick.
