### ISSUE TITLE
Terminating all Deals/Sectors is potentially too slow

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#483]
From builtin/miner/miner_actor.go: `terminateSectors` --
`// TODO: red flag that this method is potentially super expensive`

 and `requestTerminateAllDeals`:
```
// TODO: red flag this is an ~unbounded computation.
// Transform into an idempotent partial computation that can be progressed on each invocation.
```

These two TODOs stem from the root problem that "it loads all the deal IDs into a slice and makes a method call with it to terminate them."

**Comment by Stebalien** [comment]
Is the issue:

1. Loading all sectors one by one?
2. Calling OnMinerSectorsTerminate with a large array? We can solve this by batching but it won't reduce the overall time.
3. Handling all expired sectors at the end of the proving period? I'm not sure how to fix that other than by expiring deals _before_ the proving period ends. But that seems like a potential nightmare.

I assume the problem is 2, right?

**Comment by anorth** [comment]
1. Loading all the sectors is bad. This is #411 , but our ideas to resolve that won't help here (because we need the deal ids)
2. Yes, this is the crux. Batching is probably part of the answer. Putting the dealIds in a bitfield will probably make a significant difference too. But yes, I see. 

One angle I have been thinking about, which may help here, is spreading sector termination work out over multiple epochs. If we can *mark* a sector terminated quickly, but then incrementally process small chunks of terminated sectors over a range of some epochs, we can spread the load out enough not to impact block validation time too much.

Also if a sector is terminating at its scheduled expiry, we should not need to inform the market actor at all (but currently do). So we can restrict this a bit to only unexpected terminations. For explicit miner termination, we can force them to batch. But for faulty sectors we still have to deal with it.

Maybe there'll be a possibility of error right around deal end epochs that we'll notify the market actor too late to slash the miner? But so close to the end of the deal, maybe we can stomach that.

**Comment by anorth** [comment]
Cleaning up the termination logic to distinguish the two cases would be a good step.
