### ISSUE TITLE
Implement committed capacity sector upgrade with new sector

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#485]
We wish to allow a miner to replace a "committed capacity" sector (with no deals) with a sector that does have deals, without penalty for terminating the CC sector early. An [earlier attempt](https://github.com/filecoin-project/specs-actors/pull/398) structured this as upgrading the sector in-place, re-using the sector ID, but this introduced a bunch of complications.

It would be simpler to actually just use another sector. We can treat the "upgrade" as a license to terminate an empty sector before due without paying any penalties. This results in

- only one sector lifecycle flow, with no cycles
- static correspondence between sector id and CommR/CommP, deals, and on-disk data

In implementation, this amounts to attaching the ID of a CC sector to terminate when a new deal-ful sector is PreCommitted, and then actually terminating that sector as an on-time (no penalty) expiry when the new PoRep is verified.

Constraints etc:
- the old sector must have no deals
- the new sector must have at least one deal
- both sectors must be the same size (trivially true in present implementation)
- the new sector's expiry must not be sooner than the old sector's expiry
- the miner must post a new initial pledge for the new sector, based on it's (higher) power
- the pledge amount _recorded_ for the new sector should be max(old sector pledge, new sector pledge)

**Comment by anorth** [comment]
This new workflow should come with tests concurrent with implementation.

**Comment by irenegia** [comment]
> I don't think there are any constraints on the new sector other than that is has at least one deal. It must be the same size because a miner actor has a fixed sector size.

I believe that we need to add the condition that the new sector quality is set to 1 for the first proving period. Would this be possible to implement?

**Comment by anorth** [comment]
@irenegia unfortunately I don't think so. We need to rely on a sector's power being a constant in order to avoid expensive state-loading and calculations.

We could possibly revisit the deferring of power for a new sector until the end of the proving period in which it is committed. It's more complex in implementation and annoying for testing (b/c have to wait a whole day for anyone to gain power). If we change it, I want to change it for all new sectors (but I think research would prefer that anyway).

**Comment by nicola** [comment]
Constraints to be added to your list:
- PreCommit/ProveCommit of the new sector must indicate the sectorID they wish to upgrade. These methods will fail if the sectorID that they are planning to upgrade is faulty or declared faulted.
  - Side effect: if a CC sector become faulty in the middle of an upgrade, then it cannot be upgraded and a new precommit/provecommit  attempt must be done.
- At ProveCommit the previous sector is terminated (so that there is never two sectors counting for power backed by a single pledge)

**Comment by anorth** [comment]
Ack, except:
- on success, the previous sector is terminated _at the end of the proving period_ (because that's when all sector terminations are processed, and we can't mutate deadlines during the period)
- thus, the previous sector may be scheduled for wpost after being "replaced". It will be independently penalised if the post is missed.

I have assumed these are not a problem, since both these would hold if no upgrade were being performed, and the first sector just happened to be scheduled for expiry. The result is strictly more proven storage.

Again, the story is that we treat the "upgrade" as a license to terminate an empty sector earlier than it was already scheduled.

**Comment by nicola** [comment]
Does this mean that the two sectors could be required to be proven during the WindowPoSt?

**Comment by anorth** [comment]
@nicola and I talked and I think we're agreed everything here is ok, at least up to issues that affect all sectors and aren't specific to CC upgrade. This two sector proposal does mean that a miner will need to maintain both the old and the new sector for a period of time (<1 day) while waiting for the old one to expire. This means miner's will need at least some buffer space in their set-up to process the upgrades.

**Comment by zixuanzh** [comment]
Two comments to add, 

1. In the constraint for **PreCommit for a Sector Upgrade**, maybe this is too obvious but the old sector needs to be already Proven (not in PreCommit) and active (not faulty or declared faulty).

2. Regarding the last message, I am okay with this because miners need to reseal to upgrade at the moment (that's probably the dominant cost anyways). I dont fully understand why we need the old sector to be proven till the end of the ProvingPeriod if power update happens at ProveCommit and the sector must be active before that happens. Will appreciate a brief explanation.

**Comment by anorth** [comment]
1. Yes
2. The need comes from impl complexity. Sector termination accounting for all sectors happens at end of PP. So the old sector will still have power, too. It may be possible to change this, but that will be for all sectors, not a special case here.
