### ISSUE TITLE
Multisig actor construction -- handle duplicate signers

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#497]
From #443 adding constraints to multisig construction I received this review comment
```
A couple other cases we should consider checking:
...
* Duplicate Signers -- e.g. signers = addr.Address{"alice", "bob", "bob", bob"}
...
```
It's not clear that we want to restrict duplicate signers but it's seemingly never a useful thing to do so the restriction seems fine.  Although I lean towards allowing this since it appears harmless I'm filing this for design discussion on @anorth's request.

**Comment by frrist** [comment]
One reason for disallowing it -- Permitting duplicate signers allows for a multisig actor to be created that is incapable of executing transactions (ever), for example:

1. construct multisig actor requiring 4 approvals and the following signers "alice", "bob", "bob", bob".
2. alice proposes a transaction (1/4 approvals)
3. bob approves the transaction (2/4 approvals)

The transaction (requiring 2 more approvals) can never be executed since duplicate approvals are rejected.
https://github.com/filecoin-project/specs-actors/blob/6aacf90f3f09d57ebad05ba896bcee1d4efccfc8/actors/builtin/multisig/multisig_actor.go#L325-L330

While is fairly harmless, since alice can always cancel their proposed transaction, it's poor UX.

**Comment by ZenGround0** [comment]
In light of the above clarification this seems like an important check.
