### ISSUE TITLE
state reuse across send boundaries

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#508]
We have at least one place where we load state, send a message, then reuse the state in a transaction. Unfortunately, cborgen doesn't clear struct state (yet, https://github.com/whyrusleeping/cbor-gen/issues/21).

The "extra" field could get deleted before the transaction is called (maybe?), then re-persisted in the transaction.

https://github.com/filecoin-project/specs-actors/blob/07f794c2d0eedf7ee9b8a27d53baac7d653bbd37/actors/builtin/paych/paych_actor.go#L189

The fix for this is probably just to merge https://github.com/whyrusleeping/cbor-gen/issues/21, but I wonder if we want some additional checks. We could check `reflect.ValueOf(st).IsZero()` every time (or add an `IsZero` check to state).

**Comment by anorth** [comment]
Wow, nice catch.

I think this case is benign, because the `Extra` is a field in the params to the method call, rather than the actor state itself. So it won't change and isn't referenced again.

But the runtime state handle interface is definitely expecting the struct to be completely replaced with the freshly-loaded state, so this could easily cause a hard-to-diagnose bug somewhere else.

I agree the fix is probably to update cbor-gen, on the (safe) assumption that that's what the VM will use to deserialize.
