### ISSUE TITLE
Write transactions may not be enough

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#509]
Write "transactions" are actually atomic updates. Unfortunately, there's no mirror for atomic _reads_. This can lead to code like:

https://github.com/filecoin-project/specs-actors/blob/07f794c2d0eedf7ee9b8a27d53baac7d653bbd37/actors/builtin/miner/miner_actor.go#L454-L558

This code:

1. Loads the state and a store into an `st` variable.
2. Sends messages.
3. Repeatedly _reloads_ the state into `st` in the transaction, but never reloads the `store`.
4. Uses the state and the store together.

The code may be just fine, but it's hard to reason about.

There's a TODO (#476) about performing all these updates after the loop, but it would be nice if the transaction system made it harder to write code like this. 

One solution would be to introduce read transactions. We'd still be able to copy state out of the read transaction, but we'd have to be explicit about it. Of course, this could make the code even more painful to write, making all this worse.

To avoid re-using state objects, we could use some kind of initialized flag. Or we could just store a lookaside table to record "used" state objects (`map[interface{}]struct{}`).

I'm not familiar enough with the code to know what we _should_ do here, or even if this is a real problem. It just smells a bit funny.

**Comment by anorth** [comment]
The "store" is just a wrapper around the the runtime's Put/Get methods, adapting the API for use as an ipld.CborStore. If we adjusted the API appropriately the adapter wouldn't be needed. There's nothing wrong with this part of the pattern.

I'm not sure there is a real problem here. There is potential for accidentally reading stale state, if it is mutated during a `Send` and not re-loaded. An earlier version of the runtime did structure readonly state access as a "transaction" in the same way as writes, but Go type system limitations make it unreasonable to prevent access of the state object after the transaction ends anyway (it can't be lexically scoped without introducing convoluted loading incantations), so we just dropped the callback.

The linked code is not expecting the state to change during the call to external actors in the loop. Re-loading it each time is an unfortunate cost paid by the pattern, which refactoring to batch will resolve.

**Comment by Stebalien** [comment]
We've fixed all the relevent cases. I'd prefer to have better transactions, but this is good enough for now.
