### ISSUE TITLE
Make repeated state updates more efficient by temporarily using an insecure hash function

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#539]
Currently, we often update the same state repeatedly (I think?) every block. This means we spend a lot of time (I think?) hashing. Ideally, we could just defer serializing and hashing until the end, but that makes it harder to reason about correctness (to easy to accidentally share state, mutate something, etc.).

Proposal: use an insecure and/or less secure hash function to calculate CIDs (possibly with a secret seed). Then, once the block is ready, follow all insecure CIDs in the state tree, recomputing secure CIDs (in parallel).

**Comment by davidad** [comment]
Neat idea! I could imagine this being very worthwhile or not worthwhile at all; like many optimizations, my guess is that the only way to tell would be profiling data.

**Comment by Stebalien** [comment]
Yeah, @whyrusleeping says it's probably not given how fast sha256 is, and that we just need to (de)serialize less. But I have yet to see any profiles.

**Comment by ZenGround0** [comment]
Checking in @Stebalien has any new info come out convincing you that this won't speed things up?  If so I'll close.

If not I'm marking as good first issue because while this is not trivial it seems like a fun and fairly challenging standalone project for someone looking to get to know the vm system very well with at least the potential for significant impact.

**Comment by Stebalien** [comment]
I'm not convinced this is worth it. The cost of re-serializing everything is probably more.
