### ISSUE TITLE
Allow owner key to act as miner [was: while key change is in progress]

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#547]
If a miner loses their worker key, they will be unable to submit Window PoSt for at least the duration of the key change delay (which is finality). This could cost a large amount of power and fees.

While an obvious remedy is "don't lose the key", in order to make this a less catastrophic scenario for a miner, we should allow their owner key to sign some messages while waiting for the change.

If a worker key change is pending, then allow the worker or owner key to sign:
- SubmitWindowPoSt
- DeclareFaults

Aside:
The key change delay is long because this same key is also used for election VRFs. The alternative of having two worker keys, with different roles and different delays, was considered and rejected as not worth the complexity.

**Comment by ZenGround0** [comment]
A slight simplification would be to always let the owner key authorize these operations.  Miners will want to keep the same behavior only using owner key when absolutely necessary to minimize owner exposure and we can avoid the (small) extra complexity of checking that the worker is in transition before authorizing owner.  I'm saying this because I don't think allowing both options causes any security problems.

This isn't a very big improvement in complexity but falls under the category of "don't enforce conveniences" which I want us to embrace.

**Comment by anorth** [comment]
I was guided to specify "only when changing keys" by the principle of least privilege and @nicola.

**Comment by Stebalien** [comment]
Are you trying to force miners to follow the principle of least privilege by forcing them to use a separate worker key? Otherwise, if the owner key can initiate a key transition at any time (this is correct, right?) then the owner key can declare faults, submit window posts, etc. at any time anyways (by initiating a key rotation).

I'd moderately prefer to allow the owner key at all times so that nobody can be fooled into thinking the owner key can't perform these operations.

Also note: the miner is likely going to end up wasting some gas at the end of key rotation when the owner key is atomically replaced.

**Comment by anorth** [comment]
@Stebalien's reasoning is good. @nicola disallowing the owner key normally is misleading, I also think we should allow it all the time.

**Comment by anorth** [comment]
By the same logic, the owner can effectively call any method currently restricted to the worker, not just the whitelist of two above. For clarity of the true behaviour, we should probably just allow the owner anywhere we currently require the worker.

**Comment by nicola** [comment]
I may be ok with that, but it's important that we don't use the owner key for leader election.

**Comment by nicola** [comment]
We could do this, but this will require a change in DeclareFaults, DeclareFaultsRecovered.

Giving the miner to use either key breaks our reliance on sequentiality of messages (and rejection of messages with the same nonce).

Here is the explanation for DeclareFaults:

If the DeclareFaults message is evaluated after the deadline's FaultCutoff epoch and before Close, it will fail. ✅

If the DeclareFaults message is evaluated after the deadline's Close epoch, it is considered for the next submission for the same deadline:
- If the sector continues to be faulty, then DeclareFault will fail (since it is declared sectors that are already faulty) ✅
- If the miner signed new messages with the same or higher nonce, the DeclareFault will also fail. ✅
- If the miner uses a worker key to sign a DeclareFault and another worker key (after WorkerKeyChange) to sign a DeclareRecovery, the DeclareFault will fail. ✅

Back to this proposal:
- By allowing owner key only during WorkerKeyChange, the last point still works. ✅
- By allowing owner key to be used interchangeably, the last point will fail: the miner uses an owner key to sign a DeclareFault and worker key to sign the DeclareRecovery. If the DeclareFault is delayed it will be executed after DeclareRecovery (instead of failing!) ❌


Now, this is a very nuanced situation and only a malicious setting could trigger this edge case to happen.


If it is delayed even further, it will be considered for the next submission for the same deadline unless the nonce of the DeclareFault message is already used (for example by another transaction from the miner, e.g. DeclareRecovery or SubmitWindowedPoSt) and will not cause the sector to fault.

Happy to explain later.

**Comment by anorth** [comment]
I don't see how this is an attack or a problem. An operator who signs messages with the two different keys loses control over the order of execution between the keys (unless they wait), but that's not an attack. They might screw it up and have some sectors declared faulty that they didn't intend. You might have to explain the issue here.

> If the miner signed new messages with the same or higher nonce, the DeclareFault will also fail

No, not necessarily. With the same nonce, maybe but nondeterministic. Higher nonces are ineligible for execution until prior ones execute.

>If the miner uses a worker key to sign a DeclareFault and another worker key (after WorkerKeyChange) to sign a DeclareRecovery, the DeclareFault will fail. 

No? Why? I don't see how anything is enforced here.

**Comment by nicola** [comment]
This is a problem only when a miner is using an owner key to sign a DeclareFault and an DeclareFaultRecovered with a worker key and their DeclareFault gets delayed.

> No, not necessarily. With the same nonce, maybe but nondeterministic. Higher nonces are ineligible for execution until prior ones execute.

I think we agree. All I am saying is that if we have two messages with the same nonce and one gets delayed (DeclareFault) it will fail.



> If the miner uses a worker key to sign a DeclareFault and another worker key (after WorkerKeyChange) to sign a DeclareRecovery, the DeclareFault will fail.

If a miner changes a worker key, their DeclareFault with the old worker key should be rejected.

**Comment by anorth** [comment]
>> If the miner uses a worker key to sign a DeclareFault and another worker key (after WorkerKeyChange) to sign a DeclareRecovery, the DeclareFault will fail.

>If a miner changes a worker key, their DeclareFault with the old worker key should be rejected.

Oh, if the declare fault does not arrive on chain before the worker key change, yes. The miner can't control that ordering _unless_ they can use the owner key to submit the DeclareFault in the first place.

I'm still not clear whether there's a security problem here, or just ergonomics.

**Comment by nicola** [comment]
I think I am just worried about miners submitting critical transactions that may get postponed and be harmful.

This can be solved by adding expiration to a DeclareFault transaction, so even if postponed, can be ignored.

**Comment by Stebalien** [comment]
OT: do we have a "cancel" transaction? I.e., submit a no-op transaction that invalidates all transactions with lower nonces?

**Comment by anorth** [comment]
@Stebalien we don't formally, but I think we intend to implement "replace by fee", which means that a higher paying transaction with the same nonce will replace a lower-paying one. It's not a fully deterministic mechanism, though.

**Comment by anorth** [comment]
@aarshkshah1992 I'm re-stating the simplest proposal here:

> By the same logic, the owner can effectively call any method currently restricted to the worker, not just the whitelist of two above. For clarity of the true behaviour, we should probably just allow the owner anywhere we currently require the worker.

Could you update your PR to implement that? I expect it to simplify the testing somewhat.

**Comment by anorth** [comment]
With #942 rushing in we'll end up with different keys with different roles anyway. If a miner can set new control addresses, used for signing messages but not blocks/elections, and those keys have no delay in becoming active, then we don't need to allow the owner key after all.
