### ISSUE TITLE
Add logging hook to runtime

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#564]
Esoteric error cases like recent work handling unexpected errors from the cron actor want logging for differentiating different branches.  Miner and network debugging UX will be greatly helped by this.  

@anorth has some thoughts on this related to extending the runtime interface.

**Comment by anorth** [comment]
Right. I think the best option here is to add a `Log` method to the runtime, along side the stub for opening a trace span. This delegates the back-end entirely to the embedding implementation, pretty much without restriction (including no-op). It also avoids the need to import any additional dependency into this repo where every unexpected change could cause a fork. The impl will have to do some simple, if possibly verbose, adaptation to some concrete logger.

```
type LogLevel int
const (
	DEBUG = iota // Match the level enums for the backend Lotus actually uses
    INFO
	... etc
)

type Runtime interface {
  // ...

  Log(level LogLevel, msg, args ...interface{})
}
```

There are other semantically equivalent designs such as returning a logger object from the runtime so that it can be passed around. We don't expect extensive use of this though, so no need for too much sophistication.

**Comment by Stebalien** [comment]
It would be nice to get some structured logging. Or at least be able to turn logging on on an actor-by-actor basis. For example, I could see miners wanting to log only messages relevant to themselves.
