### ISSUE TITLE
Refactor how Worker addr interacts with its PK

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs-actors#57]
From https://github.com/filecoin-project/specs-actors/pull/49#discussion_r370765166

We need an id -> pubkey lookup and then a refactor where `Worker` is concerned.

I understand this is necessary due to caller validation as is done here.

For reference Lotus, does not require this step, see https://github.com/filecoin-project/lotus/blob/be6badc6a504830f4887ffb01ac3521377f629fe/chain/actors/actor_miner.go

**Comment by anorth** [comment]
We already have this system, but I struggled to explain it in the linked comment.

The canonical address for an actor is its ID-address. We have a need to determine if an account actor has an associated BLS key or not. This can't be directly inferred from its ID-address. Instead, code that wants this information should send a message to the account actor (using its ID-address) requesting it's pubkey address, and then inspect that.

The account actor doesn't currently have that method. We should add it, and then invoke it from the miner actor.

Lotus doesn't validate that the miner has a BLS key up-front, which is why you can't observe that pattern here. It makes sense to enforce it in the miner actor's constructor and key-change methods, though.

cc @whyrusleeping
