### ISSUE TITLE
Market Actor: Should we be able to Terminate the same deals twice

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/specs-actors#589]
Currently, it is possible to mark the same deal as terminated twice by calling `OnMinerSectorsTerminate` twice with the same dealID. The `SlashEpoch` on the deal will be the last `CurrentEpoch` it was called at.

Is this the expected behaviour ?

@anorth

**Comment by anorth** [comment]
I think that we should allow the call without aborting, but not do anything if the deal is already terminated (just as if it were already ended naturally). So it should not charge more penalty or change SlashEpoch. Charging more fees would be definitely wrong, since the collateral is only locked up once.
