### ISSUE TITLE
Set a sensible payment channel settlement delay

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#709]
It's currently set to 1, which doesn't give the receiver sufficient time to submit their vouchers.

@whyrusleeping what delay do you suggest?

**Comment by whyrusleeping** [comment]
@anorth I want to say that an hour is sufficient, because thats plenty of time for a party who is online to notice something happening.

But doing so means that one party may be able to cheat the other if the other party is offline for longer than that time period. Given that, we probably want to move it to being one day, and set the expectation that if youre managing funds in a payment channel, you shouldnt go offline for longer than a day.

**Comment by whyrusleeping** [comment]
Let's split the difference and call it 12 hours. If users want it to be larger, they can make sure to include a `MinSettleHeight` on their vouchers (which doesnt quite do the same thing, but definitely helps)
