### ISSUE TITLE
Sector Lifetime bounds

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#734]
We need to change the enforced sector lifetime bounds.  The maximum sector lifetime is already enforced but the parameter needs to change to 366 days.

We are not yet enforcing sector minimum lifetime but need to do so at precommit time.  The minimum sector lifetime parameter is 180 days.

**Comment by anorth** [comment]
Someone somewhere said

> MaxSectorLifetime - this is denominated in a date since launch

This was news to me and needs specifying. @nicola @zixuanzh please describe requirements here if you want something like that to be implemented.

**Comment by whyrusleeping** [comment]
@anorth maximum and minimum lifetimes will not be specified in terms of a time since launch, it will just be a number of epochs from sector start.

That said, the research team wants to include a thing on chain that will prevent the submission of new PoReps after a certain epoch.

I'll leave it to them to provide exact numbers here
