### ISSUE TITLE
Don't vest sector initial pledge, just lock it up for sector lifetime

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#757]
At present, a sector's initial pledge is locked up in the vesting table, and unlocks and vests over some period that is independent of the sector's lifespan. Since it vests, there's no guarantee that the miner has locked-up value equal to the sum of their initial pledge requirements, so we have to add more checks for that explicitly anyway (#415).  This is very harsh for miners since their pledge can be locked up for longer than the sector lifetime, and the vesting configuration is coupled to our expectations of sector lifetime etc.

This is also a huge performance problem: [AddLockedFunds dominates state read/write activity](#502) on chain validation, because every sectors commitment write a bunch of vesting entries (and we expect #sectors > #blocks).

Compare with precommit deposit, which is locked up on precommit and released immediately on proof, no vesting.

Instead of vesting, we can just lock up the pledge directly, like precommit deposit: increment on provecomment and decrement on termination (we already record this number in miner state).

If not vesting, we have to determine a priority of coverage by funds, and how to process penalties, which previously always came from locked vesting funds (the precommit deposit is a separate bucket that cannot be tapped for penalties). I propose that a miner's balance is spoken for by, in order:
- pre-commit deposits, PCD
- vesting ("locked") funds, LF
- initial pledge, IP

As invariant, balance may never fall below the sum of PCD + LF w/o triggering [miner bankruptcy](#627). When vesting funds are penalised, the funds to burn are unvested first, until LF=0.

Upon penalisation [edit: see comments below with change to this]
- If balance exceeds PCD+LF+IP, burn funds until they are equal
- then while balance exceeds PCD+LF, burn funds, leaving IP un-covered
- then, while balance exceeds PCD, unlock and burn from LF (IP still un-covered)
- then when LF=0 and balance=PCD and a fee needs to be paid, bankrupt

This is in all cases penalising the funds that are most freely available, and hence valuable, to the miner.

While balance < PCD+LF+IP, a miner will be prevented from withdrawing or committing a new sector (#415). They can deposit new funds with a simple send until they cover IP again.

**Comment by anorth** [comment]
An alternative that wouldn't solve the performance problem at all but would be slightly better than status quo for miners would be to use a dynamic vesting schedule that's calculated from the sector's lifetime. Has a bunch of problems though, like:
- upgraded CC sectors' pledge would remain locked
- how to handle sector extension when the vesting is already set in stone

**Comment by nicola** [comment]
I agree with the overall goal. There is a security constraints that currently requires IP (or a large portion of it) to be always present throughout the sector lifetime.

**Comment by davidad** [comment]
To the end of trying to keep IP covered at all times, I think we should burn from LF first, before burning through IP. I think the net effect of this is to make it less common that miners need to top up, but I think this makes sense as a policy. Conceptually, there's no LF "requirement"; the amount of LF a miner has earned just is what it is. Only once the LF buffer is exhausted do we need to start eating IP and requiring top-up.

**Comment by anorth** [comment]
Penalising from LF first is fine by me. I note that LF is _future money_ for the miner, contingent on work they must continue doing, rather than money they actually have. So a rational agent will apply a discounted cash flow analysis (probably with a fairly high discount rate), which makes it worth a bit less.

But conceptually, totally fine, slightly more generous, and will definitely reduce the need for top-up.

Note: this is all within the constraint that I have received from CE that LF from old sectors rewards can't actually count towards covering the IP of new sectors, but new IP for each new sector must be posted independently.

**Comment by acruikshank** [comment]
@ZenGround0 and I started in on this and ran into a few complications. We think we've worked it out, but it involves some assumptions that are not implicit in the conversation above.

Assumptions:
1. We will allow miner's to go into "IP debt" where their balance does not cover their initial pledge requirement. **alternative:** miner bankruptcy after locked funds run out. This is harsh but makes the following problems go away.
2. When penalizing miners, we will take from locked funds first, then initial pledge. IP debt implies locked funds are zero. **alternative:** Do it the other way around, but, if anything, that makes the complications worse.
3. `InitialPledge` will be included in the power actor's Total Network Pledge. This complicates accounting. **alternatives:** Don't track it at all which is inconsistent with the previous state where IP was part of locked funds. To track InitialPledgeRequirement (IPR) instead. This simplifies accounting but double counts IP debt as both IPR and burnt funds.
4. We will track initial pledge with two variables, `InitialPledgeRequirement` and `InitialPledge` which will only differ when in IP debt. **alternative:** Ccompare the miner's balance against IPR locked funds and precommit deposits to determine if they're in debt. The problem with this is that every miner message could add value and erase IP debt which (assuming 3) would require a power actor update.
5. `AddLockedFunds` will pay down IP debt before adding locked funds to the vesting schedule. This means the reward actor doesn't need to deal with whether the miner is in IP debt, and provides a mechanism to get out of debt. **alternative:** Use a separate function to manage initial pledge. This would just export complexity outside the miner actor.

We will treat the initial pledge requirement like a tranche of locked funds with a different vesting schedule. Funds to this tranche are last to leave and first to return, but otherwise fungible.

cc @anorth @nicola @zixuanzh @davidad

**Comment by anorth** [comment]
My apologies that things weren't quite clear enough here for you to intuit my intentions. Great work, but I think we can do something simpler.

1. IP debt: yes. This refers to a case where balance < PCD + LF + IPR
2. Penalize LF before IP: yes, as @davidad's comment above
3.  Track IP: No, track only the requirement. When I say IP I am always referring to the _requirement_. Track IPR only and communicate with power actor only in the same way as before
4. Track IP and IPR in state: see above. Don't update the power actor when balance changes
5. AddLockedFunds pays IP debt: no, this breaks the constraint that "LF from old sectors rewards can't actually count towards covering the IP of new sectors"

The sticking point that neither I nor commenters above had thought through before is the effect on the power actor's `TotalPledgeCollateral` variable, which is tracked so as to estimate the circulating money supply. You have proposed accounting for pledge coverage separately and explicitly from the requirement in order to track the total pledge collateral explicitly. I think this is too complicated to be worth it.

Consider the alternative of tracking only changes in pledge requirement, and leaving the coverage of it implicit. You interpret this as "double-counting IP debt as both IPR and burnt funds" after a penalty is paid from it. Alternatively, I interpret it as already accounting for the funds that the miner must obtain and deposit in order to meet their collateral requirements.

At present, a miner has some scope to continue operations in a state of IP debt, but that is easy to remedy. We generally want miners to meet their pledge requirements and it's easy for us to tweak something to enforce it, such as requiring IPR coverage in order to (a) Window PoSt, or (b) win a block. I think one or the other of those are likely follow-ups to this.

If `TotalPledgeCollateral` is an overestimate, due to un-covered pledges, then the circulating money supply will be estimated as slightly smaller than its true value, until the pledge requirements are topped up. This in turn will slightly reduce pledge requirements for future sectors, generally benefitting other miners rather than the delinquent.

**Comment by anorth** [comment]
The overriding motivation for this change is to simplify (and reduce state churn). If it gets more complicated, it's not an improvement.

If we were going to require new exported methods for shuffling balance into explicitly tracked IP lock-up, I'd probably prefer the existing vesting approach (maybe with per-sector vesting schedules).

**Comment by anorth** [comment]
Re-stating the penalisation algo, as I interpret @davidad's suggestion:

- While LF > 0, unlock and burn from LF
- then, while balance exceeds PCD, burn from balance (possibly leaving IP un-covered)
- then when LF=0 and balance=PCD and a fee needs to be paid, bankrupt


Since pledge requirement/coverage and vesting rewards are now handled separately, it might make sense to track the totals separately in the power actor (even if we do end up accounting for the balance separately from the requirement): `TotalPledgeRequirement` and `TotalLockedRewards`. They would still change only at the places where `TotalPledgeCollateral` already changes in the existing code. This can wait for a follow-up.

**Comment by anorth** [comment]
Another policy decision to be made is how to treat new block reward paid to a miner if they are in IP debt. If we take the intuitive answer of "lock it up", then we introduce an ordering asymmetry wrt paying fees from LF first.

Say a miner has 0 LF and exactly meets IPR:
- If a reward is earned and locked, and then a penalty paid from LF, the miner still meets IPR (by generous design)
- If a penalty is paid from balance (IP debt) and then a reward is earned and locked, the miner is in IPR debt and will at some point be forced to deposit more funds

@davidad to be consistent with "the end of trying to keep IP covered at all times", we should instead put an earned reward towards IP debt first, locking up only any surplus. This would mean, however, that in some circumstances it could become available for withdrawal earlier (when a sector expires).

**Comment by davidad** [comment]
@anorth, I agree, it logically makes sense to put an earned reward toward IP debt before it goes into the LF pool.

Being in IP debt should be costly enough that it is never a good idea to go into (or stay in) IP debt in order to be able to unlock rewards sooner. (For example, as @zixuanzh mentioned in Slack, we may not even want to allow a miner in IP debt to be a block winner, which would not only solve the incentive problem but remove the edge case entirely.)

**Comment by davidad** [comment]
@anorth, I agree, it logically makes sense to put an earned reward toward IP debt before it goes into the LF pool.

Being in IP debt should (somehow) be made costly enough that it is never a good idea to go into (or stay in) IP debt in order to be able to unlock rewards sooner.
