### ISSUE TITLE
Miner.ChangeWorkerAddress: handled a pending change already exists

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#802]
The presence of a pending worker key change indicates that an unprocessed deferred cron event is scheduled to commit the change at a later date.

If the miner is allowed to overwrite `st.info.PendingWorkerKey`, they will cause an abort during the future deferred cron event.

Rather than allow this, simply abort if `info.PendingWorkerKey` is not `nil`

**Comment by anorth** [comment]
I don't think we should black out the ability to initiate a key change because one is already in progress. But we should handle it gracefully, not abort.

I propose that we want the semantics that a new key change proposal replaces an existing one, and restarts the clock. We can achieve this simply by changing the `info.PendingWorkerKey == nil` and `info.PendingWorkerKey.EffectiveAt > rt.CurrEpoch()` cases to do nothing silently, rather than abort.

**Comment by wadeAlexC** [comment]
The problem with allowing an existing proposal to replace an existing one is that in the current implementation, the cron event from the first pending change is still going to happen. Once that first cron tick executes, `commitPendingWorkerKeyChange` will abort because the new proposal has an expiration time that is in the future.

I think we should abort if a pending change already exists, so that we don't allow the miner to create cron callbacks that will definitely abort.

**Comment by anorth** [comment]
That's a fair concern. As it is, the miner will only pay about half the total cost here in gas fees. I'll move that to a new issue.
