### ISSUE TITLE
Sector Expiration Fix

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#877]
#836 rushed through a sector expiration change that [doesn't seem exactly right](https://github.com/filecoin-project/specs-actors/pull/836/files#r463510025).  I think I should have changed max sector lifetime and instead changed max extension

1. `SectorMaximumLifetime()` should be changed to 540 days from five years
2. `MaxSectorExpirationExtension` should move back to 366.  

@zixuanzh @nicola let me know if this sounds alright with you.  This doesn't matter for incentinet since it's not going to last 180 days.

@anorth FYI

**Comment by anorth** [comment]
I don't think any change is needed. We should not imply the arithmetic around subtracting 180 from 540. We should set this value based on any independent restriction that exists.

@zixuanzh's comments explicitly say there is no restriction. We could set this to max uint64 to be clear about that. Otherwise set it to equal max sector lifetime ?

**Comment by zixuanzh** [comment]
@nicola raised that there might be a need for MinSectorLifetimeExtension.

It seems reasonable to set that to the MinSectorLifetime. In other words, given a MinSectorLifetime of 180 days and MaxSectorLifetime of 540 days. Sectors can be extended at minimum 180 days at a time up till the maximum SectorLifetime (540 days) since the StartEpoch of the original sector. There is no independent restriction for MaxSectorLifetimeExtension but the practical bound is 540 - 180.

**Comment by anorth** [comment]
I'll await the promotion of "might" to "must".
