### ISSUE TITLE
Add static state methods for miner election eligibility

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#887]
A miner's eligibility for elections is conditional on some properties of state. The power state has `MinerNominalPowerMeetsConsensusMinimum` that is never invoked internally, but from the node, encoding the property of a miner meeting the minimum power requirement.

The miner state has `MeetsInitialPledgeCondition`, but we added that recently and Lotus probably aren't using it yet.

Add a single `MinerEligibleForElection` function that takes parameters as necessary (power state, miner state, current balance) to encapsulate all the relevant state predicates, including if we change them in the future.

FYI @magik6k @arajasek, or let us know if this would not be helpful.

**Comment by anorth** [comment]
Check also fee debt (#888) in the predicates.

**Comment by anorth** [comment]
Check minimum IP requirement: #933

**Comment by anorth** [comment]
Check not recently reported for consensus fault: #934

**Comment by ZenGround0** [comment]
After @anorth and @nicola have synced this issue is now expanding in scope to include running consensus eligibility conditions (5x reward of funds available + no faults in finality epochs) inside of the existing pledge / fee debt predicate.  

The `verifyXXX` function should expand to take in all of the necessary parameters and return an error so that the endpoint we give to lotus can just gather inputs from states and pass them to this function and pass along the error.

**Comment by anorth** [comment]
Please don't fold the enforcement of restrictions in miner methods with the checks for election eligibility. They are similar, but likely slightly different computations for different contexts. They will no doubt share some pieces, but we should be able to update one independently of the other.

**Comment by anorth** [comment]
Re-opening because #988 did not include the check on minimum consensus power, `MinerNominalPowerMeetsConsensusMinimum`.
