### ISSUE TITLE
Consensus fault renders miner ineligible for election until finality

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#934]
The penalty for consensus faults is to be reduced from complete miner termination down to a fee and ineligibility for elections until finality.

The consensus fault penalty (CFP) is to be `5.0` times the current per-win-count total block reward (irrespective of miner's power share), as specified in #933.

Add a `ConsensusFaultReported abi.ChainEpoch` to miner state, initially `-1`. Upon a valid consensus fault report, instead of terminating the miner:
- set `ConsensusFaultReported` to the current epoch
- charge the consensus fault penalty

The miner must have the CFP in unlocked balance because that is a condition of election eligibility.

**Comment by ZenGround0** [comment]
> The miner must have the CFP in unlocked balance because that is a condition of election eligibility.

Because consensus fault slashing conditions don't need to be satisfied by blocks actually accepted into a chain, election eligibility doesn't give us this guarantee at the time of consensus faulting.  

I propose we withdraw the consensus slash fee the same way we withdraw all other fees: 1. from vesting funds 2. from available balance 3. from balance covering IP reqs 4. marking down remainder as fee debt to be burnt upon later recovery.

@zixuanzh @anorth let me know if this is a problem
