### ISSUE TITLE
If a sector expires before faultExpiration, its expiration should not be rescheduled

### ISSUE THREAD

**Issue by lucaniz** [filecoin-project/specs-actors#957]
Following up on a [conversation](https://filecoinproject.slack.com/archives/C015KQQLQQ1/p1597153900250700) on slack, Red Team has a question on [this](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/expiration_queue.go#L260) line of the code

why are `EarlySectors` rescheduled? If a sector expires before faultExpiration, our understanding is that its expiration should not be rescheduled. 

Cc @Stebalien @anorth @nikkolasg @irenegia

**Comment by Stebalien** [comment]
More context:

All "early sectors" bitfields _after_ `faultExpiration` should be empty because we call `RescheduleAllAsFaults` (and `RescheduleAsFaults` with non-decreasing expirations. These expirations are always `roundUpToNextDeadline(currentEpoch + FaultMaxAge)` where `FaultMaxAge` is a constant.
