### ISSUE TITLE
Restrict miner capabilities around consensus fault

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#965]
Following on from #886, we wish also to restrict the same capabilities that are restricted in IP debt when a miner is reported for a consensus fault, or would be unable to be penalised for one.

Thus, in order to be eligible to pre-commit, recover faults, etc, a miner must:
- have balance fully covering IP requirement
- have _balance_ (but not IP requirement) above the minimum required by #933
- have a consensus fault mark (#934) that is empty or has expired before the current epoch

Note a subtlety with regard to the minimum IP requirement. The leader election requirement is expressed in terms of minimum IP requirement, but we can't prevent a miner from committing new sectors with a low IP requirement since committing new sectors is how they increase that value. So we instead require the miner to have an unlocked balance exceeding that IP requirement. This is imperfect, since a miner could pre-commit sectors, withdraw balance down to PCD+IPR (below minimum), and commit a consensus fault all in the same epoch.

@nicola I must express some doubts that this is really a good idea. 
- It amounts to a minimum pledge before a miner can participate at all (by committing their first sectors), even though they can't win a block anyway. Is that the actual design goal?
- Preventing election win by a miner which couldn't pay the fee makes sense, but how does preventing pre-commit or recovery help? A miner with IPR below the minimum can't possibly commit a consensus fault anyway.
- It's not well enforceable. If it's important, we'll need to do something more complicated for that minimum participation pledge

cc @ZenGround0

**Comment by ZenGround0** [comment]
cc @nicola we could use your help here.  @anorth and I believe the second bullet is overly aggressive and not helping security in the way intended.  I would like to remove bullet two from eligibility criteria for precommit, recover and withdraw.  I'd like your push back or sign off before moving forward.

**Comment by nicola** [comment]
Understood, we may have chosen an overly punitive measure because we thought it may simplify implementation. To give more background in order for you to make the best choice:

Basic requirements:
- On  point 1: "enough balance to cover IP requirements" does not have to do with consensus faults, but standard storage faults - note that these are still a bit punitive, but we will improve this after launch
- On point 2: if a miner does not have enough balance to create repay consensus faults, they should not be able to mine
- On point 3: after a consensus fault, a miner must not be able to mine or make use of their consensus fault to do some forks that let them create fake sector or pay less fees (in particular PreCommit, ProveCommit and ideally Recovery should be prevented)
