### ISSUE TITLE
Multisig actor - remove tx creator problem

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/specs-actors#98]
Undefined behavior after tx creator removal - now the 2-nd signer is tx creator.

The order described [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L31) is violated.

https://github.com/filecoin-project/specs-actors/pull/97

**Comment by frrist** [comment]
The 0th index of a `Transaction`s `Approved` slice is used to determine who the proposer of the transaction is: https://github.com/filecoin-project/specs-actors/blob/c64b47b2b1b79fa38d3c19253a7544fcf3923872/actors/builtin/multisig/multisig_actor.go#L27-L34

This value (`Approved[0]`) is inspected when `Cancel` is called: If the caller is not the proposer the call will fail: https://github.com/filecoin-project/specs-actors/blob/c64b47b2b1b79fa38d3c19253a7544fcf3923872/actors/builtin/multisig/multisig_actor.go#L176-L179

The `Transaction`s `Approved` slice is only ever modified (appended to) in `approveTransaction`: https://github.com/filecoin-project/specs-actors/blob/c64b47b2b1b79fa38d3c19253a7544fcf3923872/actors/builtin/multisig/multisig_actor.go#L336-L337
meaning it is never the case that the proposer of a transaction cannot be found or that the 2nd signer is incorrectly considered the transactions proposer.

-----------------------------

A separate but related issue exists when a call to either `RemoveSigner` or `SwapSigner` results in an Approver of a transaction being removed from the `Signers` field: https://github.com/filecoin-project/specs-actors/blob/c64b47b2b1b79fa38d3c19253a7544fcf3923872/actors/builtin/multisig/multisig_state.go#L14-L15

Since `approveTransaction` does not check if a `Transaction`s `Approved` slice contains valid signers before executing it: https://github.com/filecoin-project/specs-actors/blob/c64b47b2b1b79fa38d3c19253a7544fcf3923872/actors/builtin/multisig/multisig_actor.go#L344-L367

this can result in a scenario where a `Transaction` has an approval from an addressed that is not contained in the `Signers` slice. 

This raises a couple questions:
- Are approvals from addresses that are no longer signers considered valid? This is how the code reads today.
- (Or) Should `RemoveSigner` and `SwapSigner` first check if the address being removed from the `Signers` slice is listed as an approver of a transaction before removing?
- (Or) Should `approveTransaction` first check if the Approvers in the transaction are still Signers before executing it?

**Comment by anorth** [comment]
@frrist I do not follow what the problem is in the first half of the description. I am inferring you think there is one because you then say "separate but related issue". But if you're instead confirming that you think everything is ok, 👍 .

For the second one, yes I think it is a simple and reasonable policy that approvers are only checked for being valid signers in `approveTransaction` and thus, because signers can change, a transaction may have an approval from a party no longer a signer (but was a signer when they approved it). In fact this is probably desirable behaviour. The name "proposer" becomes a bit misleading, perhaps we could call it "owner" or "administrator", though I don't think it's really worthwhile.

I would welcome pointers to clear prior art here that may have adopted different policies based on real world experience.

**Comment by anorth** [comment]
> The second half is a problem, should we just adapt this issue to address that?

Yes please. I think you could take over #97 (or at least include commits from there to give co-authorship credit).
