### ISSUE TITLE
Miner: Remove ChangeWorkerAddress reliance on cron

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#982]
`Miner.ChangeWorkerAddress` relies on a cron callback after `WorkerKeyChangeDelay` epochs to commit the pending key change. This should be avoided, as cron is a critically-important system; callbacks should only be added if they are absolutely necessary.

#### Recommendation

There are a few possible ways to implement this. Here's an option that requires relatively few changes:
* If `params.NewWorker` is `nil`, treat the invocation as a "commit" action, and commit the pending change (as long as the appropriate delay has passed).

Resolving this will make #806 redundant.

**Comment by anorth** [comment]
@nicola this was discussed with @sternhenri and @jzimmerman when ChangeWorkerAddress was implemented.

https://github.com/filecoin-project/specs/pull/776#discussion_r363632872

There was some concern about using this to maintain an option on two different worker keys. Can you take a look?

**Comment by nicola** [comment]
I think we could avoid the Cron event. A possible way to do this: the miner calls ChangeWorkerAddress, the old is marked with an expiration date and the new key is saved. Any time that the miner actor is called, the actor checks if the old key has expired, if so, it gets replaced. (I wonder if we can use similar techniques for some types of faults)

**Comment by wadeAlexC** [comment]
If the concern is maintaining an option on 2 different worker keys, there could be an expiration on the change - essentially, a range of epochs during which the change could be committed.

And if we want to minimize changes to the Miner's process, something similar to what @nicola suggested would work. I would recommend not checking the worker key change in every method, as it may add a lot of clutter. IMO maybe putting this only in `SubmitWindowedPoSt` (maybe also precommit/provecommit).

So, in sum:
* `ChangeWorkerAddress` should:
  * Store a pending change along with an effective epoch (same as it does now)
  * Remove `enrollCronEvent`
  * If `params.NewWorker == nil`, check if there is a pending change. If it is valid, commit the change. Change is valid if `CurrEpoch >= pending.EffectiveAt && CurrEpoch < pending.EffectiveAt + KeyChangeExpiry`
* `SubmitWindowedPoSt` should check if there is a pending change. If there is, and it's valid, commit the change. See above for criteria.

**Comment by sternhenri** [comment]
Is there a potential problem having to do with the fact that this gives a miner an option as to whether to trigger the change or not (by submitting a windowed post or not). I don't see it, but strictly speaking because this is now "triggered" (instead of it being done by the cron) we've increased adversarial power... Just asking.

**Comment by anorth** [comment]
Related to #806

**Comment by nicola** [comment]
I like @wadeAlexC proposal. 

The edge case that I see is when a miner does not have windowPost requirements (e.g. has not sectors or all sectors are faulty or all sectors are expired). Hence why I proposed adding it to all miners' calls.

This could be solved with an explicit command "ConfirmUpdateWorkerKey"

**Comment by wadeAlexC** [comment]
> Is there a potential problem having to do with the fact that this gives a miner an option as to whether to trigger the change or not (by submitting a windowed post or not). I don't see it, but strictly speaking because this is now "triggered" (instead of it being done by the cron) we've increased adversarial power... Just asking.

My proposal should solve this for active miners, as they will have to submit PoSts or lose power / be penalized.

As @nicola says, the edge case is for small/inactive miners that may not need to submit PoSts. For this case, I think the `KeyChangeExpiry` param + additional implementation in `ChangeWorkerAddress` will allow those that don't need to PoSt to commit the change within a reasonable time period. 

That said, I'm not enthusiastic about continuing to overload `ChangeWorkerAddress` with additional edge cases (in this case `params.NewWorker == nil` attempts to commit a pending change). If it's trivial to add a new method `ConfirmUpdateWorkerKey`, that would be my preference.

**Comment by sternhenri** [comment]
> My proposal should solve this for active miners, as they will have to submit PoSts or lose power / be penalized. 
Specifically what I'm asking is can we envision a case in which a miner would rather lose power/ be penalized than have a key change go through. Preferably, once you commit to a future key change, you should not have the ability to stop it occurring (even if a miner rationally would not). This adds power to byzantine attackers, though I don't think it's a show stopper.

Your point on adding edge-cases is absolutely right however. This system should work the same for everybody, if everyone can use `ConfirmUpdateWorkerKey,` great. Otherwise, I still think cron is preferable. I would argue that changing keys is a critical part of the system (given the fact that a key change could be triggered by a security consideration eg).

**Comment by anorth** [comment]
From what's been discussed so far, I think @wadeAlexC's original proposal is best, perhaps with the expiration too. @nicola doesn't seem concerned about the optionality.

We cannot avoid the ability to stop the change occurring: even if we used cron, a miner could just initiate a key change back to their original key before the first one took root.

Another alternative: every miner already gets a cron call every deadline. We could apply the key change at the first one after the delay? That's still unstoppable (though, as above, I don't think that achieves anything).

**Comment by sternhenri** [comment]
> even if we used cron, a miner could just initiate a key change back to their original key before the first one took root.

I don’t actually think that’s true: iirc you can’t initiate a new key change in the actor code until the first one has completed. 

With that said, as stated, I don’t think my concern is worth halting this over (And can’t see a specific attack it leads to) so if you’ve all come to a preferred solution > cron, I def think you should move forward w it!

**Comment by anorth** [comment]
> you can’t initiate a new key change in the actor code until the first one has completed

That's not the case any more. But @nicola please have RT check this is ok.

**Comment by acruikshank** [comment]
After reading through this, I'm picking from a few options that I believe everyone has agreed or not-vehemently-objected to:

1. In `ChangeWorkerAddress` we will store the new address as `UpdatedWorker` and `UpdatedWorkerValidAt` in miner state. If values already exist, we will rewrite them. We will not add a cron job.
2. We will add `miner.ConfirmUpdateWorkerKey` (since it is as trivial as overloading `ChangeWorkerAddress`), that will copy the new address to the worker address in state only if `UpdatedWorker` is set and and current epoch >= `UpdatedWorkerValidAt`. If so, we will unset `UpdatedWorker`.
3. We will execute `miner.ConfirmupdateWorkerKey` logic in `handleProvingDeadline` because, as @anorth points out, it gives us deadline period accuracy whether or not the miner is PoSting. This logic itself is cheap, so the overhead should be negligible. `SubmitPoSt` is complicated enough without adding more non-PoSt related operations.

If any of this is wrong or controversial. Point it out here or in the PR to follow.
